architecture: BlazeFace
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/blazenet_pretrain.pdparams

BlazeFace:
  backbone: BlazeNet
  neck: BlazeNeck
  head: FaceHead
  post_process: BBoxPostProcess

BlazeNet:
  blaze_filters: [[12, 12], [12, 12, 2], [12, 12]]
  double_blaze_filters: [[12, 16, 24, 2], [24, 12, 24], [24, 16, 72, 2], [72, 12, 72]]
  act: relu

BlazeNeck:
  neck_type : fpn_ssh
  in_channel: [96, 96]

FaceHead:
  in_channels: [48, 48]
  num_classes: 1
  cfg_anchor:
  kernel_size: 3
  padding: 1
  loss: SSDLoss

SSDLoss:
  overlap_threshold: 0.35

AnchorGeneratorSSD:
  steps: [8., 16.]
  aspect_ratios: [[1.], [1.]]
  min_sizes: [[16.,24.], [32., 48., 64., 80., 96., 128.]]
  max_sizes: [[], []]
  offset: 0.5
  flip: False
  min_max_aspect_ratios_order: False

BBoxPostProcess:
  decode:
    name: SSDBox
  nms:
    name: MultiClassNMS
    keep_top_k: 750
    score_threshold: 0.01
    nms_threshold: 0.3
    nms_top_k: 5000
    nms_eta: 1.0